### ISSUE TITLE
mtl-2.3-rc3 breakages due to re-exports breaks

### ISSUE THREAD

**Issue by tchoutri** [haskell/mtl#102]
Hi! I am testing the rc3 on closed-source projects and I'm noticing quite a lot of breakages due to re-exports. Would it be possible to have some actionable migration data provided for the types & functions that aren't re-exported anymore?

 I understand that the maintainer team wishes to reduce the number of weird accumulations over the years, but I'm afraid without any proper tool or knowledge of what to break, it's a bit hard to plan for the migration of our very large codebases. 

Cheers!

**Comment by andreasabel** [comment]
Now one of the two weeks of testing `mtl-2.3-rc3` has passed, and major breakage has been reported.
What does this mean for the release plans @emilypi?  Are you working on a RC4?
Or are you waiting for more feedback from the community?
To be frank, I have not invested time in experimenting with RC3 since there are already reports (#101), so I am expecting a RC4.
It would be good maybe to dedicate an issue here for status updates on the release plan.

**Comment by chessai** [comment]
Resolved in ecb525a5ba3521d0059eb2396a376b2e91557cff
rc4 published on github at https://github.com/haskell/mtl/tree/v2.3-rc4
rc4 published on hackage at https://hackage.haskell.org/package/mtl-2.3/candidate
