### ISSUE TITLE
mtl-2.2.1: transformers dependency inconsistent with Hackage

### ISSUE THREAD

**Issue by WolframKahl** [haskell/mtl#47]
Downloading a fresh copy of https://hackage.haskell.org/package/mtl-2.2.1/mtl-2.2.1.tar.gz from https://hackage.haskell.org/package/mtl gives me a `mtl.cabal` file containing:
````
  build-depends: base < 6, transformers == 0.4.*
````
However, the hackage page https://hackage.haskell.org/package/mtl  claims `transformers (>=0.4 && <0.6) `.
The latter is actually needed  ─ how can these diverge?

**Comment by hvr** [comment]
This is starting to become a FAQ (meaning we should to a better job in Hackage's UI to make this more obvious) :-)

Hackage uses a scheme since 2014 where the tarball is immutable, but its meta-data, the `.cabal` file, can be revised. Hackage clients download the tarball and the respective .cabal revision and combine them at solver time.

See e.g.  http://hackage.haskell.org/package/mtl-2.2.1/revisions/

**Comment by RyanGlScott** [comment]
Indeed, the preferred way to fetch these tarballs (with revisions) is `cabal get` or `stack unpack`.

This is a tooling issue, not an `mtl` issue, so closing.
